#CMAKE最小版本要求,可修改
#BUILD_TYPE=Release,Debug  UNIT_TEST=true,false
CMAKE_MINIMUM_REQUIRED(VERSION 3.0)

PROJECT("xls")

ADD_DEFINITIONS("-D__USE_XOPEN2K8")
#-Woverloaded-virtual
#C/C++文件编译选项,无需修改
SET(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fPIC")
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")

#头文件搜索路径,可修改
INCLUDE_DIRECTORIES(
    ${CMAKE_SOURCE_DIR}/src/export/
	${CMAKE_SOURCE_DIR}/src/export/include
	${CMAKE_SOURCE_DIR}/../libcomex/out/include
)

#库文件搜索路径,可修改
LINK_DIRECTORIES(
    ${CMAKE_SOURCE_DIR}/../libcomex/out/lib
)

#依赖库,无需修改
IF(MSVC)
ADD_COMPILE_OPTIONS( /MD)
SET(PROJECT_LIB
  	${PROJECT_LIB}
	iconv.lib
)
ELSE()
SET(PROJECT_LIB
  	${PROJECT_LIB}
	iconv.a
)
ENDIF()

AUX_SOURCE_DIRECTORY(src PROJECT_SRC)

SET(CMAKE_SKIP_BUILD_RPATH TRUE)
SET(CMAKE_BUILD_WITH_INSTALL_RPATH FALSE)
SET(CMAKE_INSTALL_PREFIX ${CMAKE_BINARY_DIR}/export)

ADD_LIBRARY(${PROJECT_NAME}_static STATIC ${PROJECT_SRC})
IF(MSVC)
    SET_TARGET_PROPERTIES(${PROJECT_NAME}_static PROPERTIES OUTPUT_NAME ${PROJECT_NAME}_static)
ELSE()
    SET_TARGET_PROPERTIES(${PROJECT_NAME}_static PROPERTIES OUTPUT_NAME ${PROJECT_NAME})
ENDIF()
SET_TARGET_PROPERTIES(${PROJECT_NAME}_static PROPERTIES CLEAN_DIRECT_OUTPUT 1)

ADD_LIBRARY(${PROJECT_NAME} SHARED ${PROJECT_SRC})
SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES OUTPUT_NAME ${PROJECT_NAME})
SET_TARGET_PROPERTIES(${PROJECT_NAME} PROPERTIES CLEAN_DIRECT_OUTPUT 1)
  
INSTALL(TARGETS ${PROJECT_NAME} DESTINATION lib COMPONENT dev)
INSTALL(TARGETS ${PROJECT_NAME}_static DESTINATION lib COMPONENT dev)
INSTALL(DIRECTORY ${PROJECT_SOURCE_DIR}/src/export/ DESTINATION include COMPONENT dev)

TARGET_LINK_LIBRARIES(${PROJECT_NAME}_static ${PROJECT_LIB})
TARGET_LINK_LIBRARIES(${PROJECT_NAME} ${PROJECT_LIB})
